# Variables
@baseUrl = http://localhost:3333

# @name healthCheck
GET {{baseUrl}}/health

###

# @name getRooms
GET {{baseUrl}}/rooms

###

# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
    "name": "Teste",
    "description": "Sala teste."
}

###

@roomId = {{getRooms.response.body.$.[0].id}}

###

# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# @name createQuestion
POST {{baseUrl}}/rooms/5b023efb-3998-4ad4-8d98-e8177acae753/questions
Content-Type: application/json

{
    "question": "Quais são os ingredientes para o bolo de cenoura?"
}
